# Generated by Django 3.2.5 on 2021-08-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='forma_pago',
            field=models.CharField(choices=[('Credito', 'Credito'), ('Efectivo', 'Efectivo'), ('Tarjeta_credito', 'Tarjeta de credito'), ('Tarjeta_debito', 'Tarjeta de debito')], default='Efectivo', max_length=20),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
