# Generated by Django 3.2.5 on 2021-08-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_auto_20160224_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='imagen',
            field=models.ImageField(upload_to='imagenes/empleado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='tipo',
            field=models.CharField(choices=[('Vendedor', 'Vendedor'), ('Jefe de taller', 'Jefe de taller'), ('Gerente', 'Gerente')], default='Vendedor', max_length=20),
        ),
    ]
