# Generated by Django 3.2.5 on 2021-08-24 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_de_trabajo', '0002_auto_20160224_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='estado_reparacion',
            field=models.TextField(choices=[('Pendiente', 'Pendiente'), ('Cotizado', 'Cotizado'), ('Reparado', 'Reparado'), ('Reparado y entregado', 'Reparado y entregado'), ('Retirado', 'Retirado')], default='Pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='placa',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^[A-Z]{3}-[0-9]{3}', code='Invalid Key', message='Debe ingresar una placa valida ej: ABC-123')]),
        ),
    ]
